### PR TITLE
Fix dormant snitches still being active & snitches not changing state over restarts

### LINKED ISSUE #37: Dormant snitches send notifications
Both in-game and through Kira.

### PR DESCRIPTION
**Pull request by okx-code**
1. If a snitch changed from active to dormant or dormant to culled during a restart, it would not actually change state. This could result in a snitch remaining active indefinitely, but this would be rather rare.
2. Separately (and the original issue that prompted this fix), was that dormant snitches would still send notifications. This is because, on server startup, dormant snitches would be re-activated (if they were disabled previously) due to incorrect logic.

Fixes #37

### CODE REVIEW

File: paper/src/main/java/com/untamedears/jukealert/model/appender/DormantCullingAppender.java [hunk 1]
```diff
@@ -97,15 +97,11 @@ public void updateInternalProgressTime(final long update) {
...
-				return getLastRefresh() + this.config.getTotalLifeTime();
-			default:
-			case ACTIVE:
-				return getLastRefresh() + this.config.getLifetime();
+	private void syncNextUpdate() {
+		switch (this.databaseKnownStatus) {
+			case CULLED -> cullSnitch();
+			case DORMANT -> deactivateSnitch();
+			default -> updateInternalProgressTime(getLastRefresh() + this.config.getLifetime());
 		}
```
Comment (Protonull) [inline paper/src/main/java/com/untamedears/jukealert/model/appender/DormantCullingAppender.java:105]: Java's switch expressions are just so 🤌

File: paper/src/main/java/com/untamedears/jukealert/model/appender/DormantCullingAppender.java [hunk 2]
```diff
@@ -182,27 +177,38 @@ public void updateState() {
...
+			deactivateSnitch();
 		}
 		// Active
-		else if (this.databaseKnownStatus != ActivityStatus.ACTIVE) {
+		else if (currentStatus == ActivityStatus.ACTIVE && this.databaseKnownStatus != ActivityStatus.ACTIVE) {
 			this.databaseKnownStatus = ActivityStatus.ACTIVE;
 			getSnitch().setActiveStatus(true);
-			JukeAlert.getInstance().getSnitchCullManager().updateCulling(this, calcFutureUpdate());
+			syncNextUpdate();
+			JukeAlert.getInstance().getSnitchCullManager().updateCulling(this, this.getNextUpdate());
```
Comment (Protonull) [inline paper/src/main/java/com/untamedears/jukealert/model/appender/DormantCullingAppender.java:191]: The fact that you put a `this.` before a *method call* but not a field is immensely triggering

**Comment by Protonull** [comment]
Seems good :)

File: paper/src/main/java/com/untamedears/jukealert/model/appender/DormantCullingAppender.java (hunk 2 above)
Comment (okx-code) [reply paper/src/main/java/com/untamedears/jukealert/model/appender/DormantCullingAppender.java:191]: Don't look at the civmodern codebase then

**Review by wingzero54 — APPROVED** [review]
Thank you for fixing this
